---
- name: Fail when a wrong apt upgrade mode is given
  fail:
    msg: "Invalid Ansible apt upgrade mode given."
  when: upgrade_mode is defined and (upgrade_mode != "no" and upgrade_mode != "yes" and upgrade_mode != "safe" and upgrade_mode != "full" and upgrade_mode != "dist")
  tags:
    - package_update

- name: Upgrade all packages (rhel and others)
  package:
    name: '*'
    state: latest
  when: ansible_distribution != "Debian" and ansible_distribution != "Ubuntu"
  tags:
    - package_update

- name: Install aptitude if necessary (deb)
  apt:
    name: aptitude
    state: latest
    update_cache: yes
  when: ansible_distribution == "Debian" or ansible_distribution == "Ubuntu"
  tags:
    - package_update

- name: Upgrade all packages (deb)
  apt:
    state: latest
    upgrade: "{% if upgrade_mode is defined %}{{ upgrade_mode }}{% else %}safe{% endif %}"
    update_cache: yes
  when: ansible_distribution == "Debian" or ansible_distribution == "Ubuntu"
  tags:
    - package_update
