---
# tasks file for galexrt.package_update
- name: Upgrade all packages (rhel)
  action: "{{ ansible_pkg_mgr }}"
  args:
    name: '*'
    state: latest
  when: ansible_distribution != "Debian" and ansible_distribution != "Ubuntu"
  tags:
    - system-upgrade
- name: Upgrade all packages (deb)
  apt:
    state: latest
    upgrade: "{% if upgrade_mode is defined %}{{ upgrade_mode }}{% else %}safe{% endif %}"
    update_cache: yes
  when: ansible_distribution == "Debian" or ansible_distribution == "Ubuntu"
  tags:
    - system-upgrade
